platform :ios, '18.0'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-firebase/app/react_native_firebase'
require_relative '../node_modules/@react-native-firebase/messaging/react_native_firebase'

target 'scratchticketgenie' do
  use_frameworks! :linkage => :static
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true
  )

  use_react_native_firebase!(
    :app => true,
    :messaging => true
  )

  target 'scratchticketgenieTests' do
    inherit! :complete
  end

  post_install do |installer|
    react_native_post_install(installer)
  end
end
