platform :ios, '16.6'

# Force-disable New Architecture to avoid RNReanimated build issues for now
ENV['RCT_NEW_ARCH_ENABLED'] = '0'

require_relative '../node_modules/react-native/scripts/react_native_pods'
 


target 'scratchticketgenie' do
  use_frameworks! :linkage => :static
  config = use_native_modules!

  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => false
  )

  post_install do |installer|
    react_native_post_install(installer)
  end
end
